security:
  oauth2:
    client:
      clientId: arip
      clientSecret: s3cret
      authorized-grant-types: password
      scope: read, write
      accessTokenValiditySeconds: 3600

logging.level.org.springframework: DEBUG